### ISSUE TITLE
Discussion of 6709:2008 SR (N4611) outcome pointing towards possible revision and revision proposal (N4618) from the Japan NB

### ISSUE THREAD

**Issue by isotc211** [ISO-TC211/StandardsTracker#127]
<b>Justification:</b> Japan NB would like to propose that the PMG consider the outcome of the 6709:2008 SR (N4611) in that a number of MBs felt that 6709:2008 should be revised instead of only being confirmed or confirmed with corrections. Subsequently the Japan NB submitted a draft (N4618) showing a number of proposed revisions. the Japan NB would like the PMG to briefly discuss this in Wellington (Nov 2017).
                                     <b>Proposal:</b> revision of 6709:2008 through formation of a project team using (N4618) as a starting point.

**Comment by ReesePlews** [comment]
ISO 6709 was revised; ISO 6709:2022 was published at the end of September 2022.
