### ISSUE TITLE
Editorial correction to 19111:2019 definition

### ISSUE THREAD

**Issue by isotc211** [ISO-TC211/StandardsTracker#131]
**Justification:**
Proposed change applies to 19111:2019, which does not appear in tracker listing. (19111:2007 and 19111-2:2009 have been withdrawn).

In definition 3.1.16, at the end of the example there is a spurious right bracket. 

This definition may be used in other standards.

**Proposal:**
Change "... and 0.02 m between G1674 and G1762)" to "... and 0.02 m between G1674 and G1762". Full definition should read:

3.1.16
datum ensemble
group of multiple realizations of the same terrestrial or vertical reference system that, for approximate spatial referencing purposes, are not significantly different
Note 1 to entry: Datasets referenced to the different realizations within a datum ensemble may be merged without coordinate transformation.
Note 2 to entry: ‘Approximate’ is for users to define and typically is in the order of under 1 decimetre but may be up to 2 metres.
EXAMPLE	“WGS 84” as an undifferentiated group of realizations including WGS 84 (TRANSIT), WGS 84 (G730), WGS 84 (G873), WGS 84 (G1150), WGS 84 (G1674) and WGS 84 (G1762). At the surface of the Earth these have changed on average by 0.7 m between the TRANSIT and G730 realizations, a further 0.2 m between G730 and G873, 0.06 m between G873 and G1150, 0.2 m between G1150 and G1674 and 0.02 m between G1674 and G1762.

**Comment by ValZapod** [comment]
And also add G2139 and how G1762’ (with a prime) relates to this.

**Comment by RogerLott** [comment]
19111 Amd 2 as sent to ISO CS for DAmd ballot amends 3.1.16 exactly as @isotc211 suggested above, Change "... and 0.02 m between G1674 and G1762)" to "... and 0.02 m between G1674 and G1762" (removal of spurious right bracket).

@ValZapod comment was not implemented. Whilst it is true that this example is now outdated, it remains valid as an example and we do not want to be updating the definition for every future realization of WGS 84.

**Comment by RogerLott** [comment]
Per comment of 2022-11-15, this issue has been resolved and should be closed.

**Comment by ReesePlews** [comment]
thank you @RogerLott !

the revised definition as shown in the [ISO OBP](https://www.iso.org/obp/ui/#iso:std:iso:19111:ed-3:v1:amd:2:v1:en) is:

![image](https://github.com/user-attachments/assets/3eb09493-0ccd-4aa0-811f-bb6c2407f5e2)

the issue (#473) does remain in 19170-1 until that standard is revised.
