### ISSUE TITLE
Corrigendum 19115-2

### ISSUE THREAD

**Issue by isotc211** [ISO-TC211/StandardsTracker#135]
**Justification:**
From Foreword:
“A specified class of MI_Instrument – MI_Sensor was defined.“
From Clause 6.3.2.1:
“MI_Instrument, designations of the measuring instruments used to acquire the data;”
“MI_Sensor, a specific type of MI_Instrument;”
UML Class Diagram in Figure 2
Identifies a sensor-hosted association such that Sensors may be hosted by Instruments, and Instruments may have Sensors
Data Dictionary in Table B.4 (next slide)
Incorrectly specifies that Role name: sensor has domain MI_Instrument rather than MI_Sensor
The assigned definition “Instrument is a sensor” would make more sense as “Instrument has a sensor”.
It is questionable whether a Sensor may be hosted by more than a single Instrument, however this flexibility may be meaningful under some circumstances (e.g., over time)
XSD has the corresponding min/maxOccurs

**Proposal:**
Recommend Corrigendum to align Data Dictionary Table B.4 Row 27 to the UML Class Diagram Figure 2
Correct Definition and Range of MI_Instrument.sensor

**Comment by wilkesg** [comment]
This was addressed in the recent amendment and can be closed.
