### ISSUE TITLE
JAG: Web Map Service 1.4

### ISSUE THREAD

**Issue by isotc211** [ISO-TC211/StandardsTracker#19]
<b>Justification:</b> Web Map Service 1.4
                                     <b>Proposal:</b> Web Map Service 1.4

**Comment by rggibb** [comment]
TC211 Nov 2021/JAG: 1.4 was proposed but superceded by OGC API Maps which is underway, 
This issue can be closed

**Comment by PeterParslow** [comment]
TC211 May 2022/WG 4: asked for API Tiles to become an OGC standard, as more broadly useful than API Maps

**Comment by JanHjelmager** [comment]
Do you mean an ISO standard, as it is in the OGC pipeline to become a OGC standard?

**Comment by dsarafinof** [comment]
Jeonju : proposal to close this issue and create for OGC API
