### ISSUE TITLE
ISO/TC 211/WG 6 - Issues identified in XML schemas to support ISO 19115-2

### ISSUE THREAD

**Issue by isotc211** [ISO-TC211/StandardsTracker#235]
<b>Justification:</b> It has been brought forward by XMG that the xsd files as they associate to part 3, all four of the XSD files have miss-ordered elements, some worse than others
                                     <b>Proposal:</b> Discussion must occur or a decision made to reorder the xsds to fit the data dictionary, both for this standard and part 1

**Comment by wilkesg** [comment]
Requires XMG review to check to see if this is still valid.

**Comment by ejbleys** [comment]
The review of ISO 19115-3 identified that the ordering is important and as such the latest schemas for SO 19115-1 & ISO 19115-2 have been built and will be released as:
     https://schemas.isotc211.org/19115/-1/<namespace>/1.3/<namespace>.xsd and 
     https://schemas.isotc211.org/19115/-2/<namespace>/2.2/<namespace>.xsd
The numbering is to align with the editions of the source and versions of the schemas (as per the agreed system)
The namespace for the image: lineage; spatial representation; and content are all linked back to the 19115-1 namespaces (eg end in /19115/1/mrs/1.3; /19115/1/msr/1.3; and /19115/1/mrs/1.3) whilst the acquisition information namespace ends in /19115/2/mac/2.2
