### ISSUE TITLE
Specifying the TC211 CSL: ISO 19103 or ISO 19109?

### ISSUE THREAD

**Issue by isotc211** [ISO-TC211/StandardsTracker#274]
<b>Justification</b>

See http://isotc211.standardstracker.org/show_request.cgi?id=224

Conceptual Schema Language Requirement 1 states that “The conceptual schema shall be modelled in conformance with UML 2”, whereas in fact most of the information about how this is done (the subset of UML which we use) is in 19109 – referenced by an informative annex of 19103.

<b>Proposal</b>

Consider how much of the specification of the way TC211 uses UML as the basis of its conceptual schema language belongs in ISO 19103 and how much in ISO 19109

**Comment by heidivanparys** [comment]
This has been discussed in both ISO 19103 and 19109, and the necessary adjustments have been made (19103 is in DFIS, 19109 is out for DIS), so this can be closed.
