### ISSUE TITLE
Confusion caused by difference in ordering of attributes in data dictionaries

### ISSUE THREAD

**Issue by isotc211** [ISO-TC211/StandardsTracker#336]
<b>Justification</b>
Significant confusion has been caused by differences between the ordering of attributes in data dictionaries within published standards and the XML schemas that proportion to manage the implementation of those standards. Extreme care must be taken to eliminate those differences when publishing the XML schemas.

<b>Proposal</b>
Insist that the projects generating a standard add a tag “sequenceNumber” to each class and attribute in the UML conceptual model where the value of the tag represents the order that class or attribute appears in the data dictionary for that standard. Other rules on setting the value can assist when amendments to the standard are made.

**Comment by PeterParslow** [comment]
Appears to arise from failure to use ISO 19139-1 requirement (rule) /req/default/XCT-properties-sequence (although some may predate converting that statement from descriptive to a requirement)

Could HMMG and XMG consider whether this proposal is a good solution? If so, then presumably it has to be added to ISO 19109 and then monitored by HMMG, and ISO 19139-1 would need to be amended/revised.

**Comment by tobiasspears** [comment]
I agree with the proposal to use sequenceNumber tag values. Although Enterprise Architect (as one example) allows the user to switch between default (alphabetical) and custom, it is very easy to accidentally switch back to default ordering, losing all custom sorting implemented in the element's attributes. With this, the numbering strategy should be added to both the HMMG wiki. 

The main goal is to ensure sequence numbers are unique and reflect the intended order between the UML, XML schemas, and data dictionary. The secondary goal is to use a numbering system that allows additional attributes to be inserted between existing ones (e.g. during revisions) without having to re-sequence all of the attributes that follow the new one.

**Comment by jetgeo** [comment]
From the discussion here, and in the XMG Meeting today, we should consider including the sequenceNumber tag from ISO 19136-1 in the core UML Profile in ISO 19103.

**Comment by heidivanparys** [comment]
The sequenceNumber tag is useful for application schemas, as those are implemented in implementation schemas. So this is out of scope for 19103 and should be considered in 19109 instead. Please update the label.
