### ISSUE TITLE
Transfer of responsibility for GMW to ISO 19136

### ISSUE THREAD

**Issue by isotc211** [ISO-TC211/StandardsTracker#344]
<b>Justification:</b> GMW - Responsibility for the management of XML schemas for the GML Wrapper namespaces will be transferred from ISO 19115 to ISO 19136
                                     <b>Proposal:</b> XML schema documents for GML Wrapper objects (GMW) will be made available from https://schemas.isotc211.org/19136/-/gwm/2.0/... a at or before 2020-12-20. These will augment those < already | continuing to be>  available from https://schemas.isotc211.org/19115/-3/gmw/1.0/...

**Comment by ejbleys** [comment]
gmw namespace is referenced from 19136 in:
https://schemas.isotc211.org/19115/-1/
https://schemas.isotc211.org/19115/-2/
https://schemas.isotc211.org/19157/-/mdq/1.2.0/dataQualityResult.xsd
https://schemas.isotc211.org/19163/-1/igd/1.1.0/IE_ImageryAndGriddedData.xsd
https://schemas.isotc211.org/19163/-1/igd/1.1.0/IE_ThematicGriddedData.xsd

For consistency older schemas will retain previous reference
