### ISSUE TITLE
Correct fcc//Abstract_FeatureCatalogue substitutionGroup

### ISSUE THREAD

**Issue by isotc211** [ISO-TC211/StandardsTracker#345]
<b>Justification:</b> fcc:Abstract_FeatureCatalogue does not instantiate. Error in XSD
fcc:Abstract_FeatureCatalogue has substitutionGroup gco:AbstractObject, yet fcc:Abstract_FeatureCatalogue_Type has an extension base of cat:AbstractCT_Catalogue_Type.
a) both need to have the same base
b) both need to be cat:AbstractCT_Catalogue_Type
                                     <b>Proposal:</b> Adjust fcc:Abstract_FeatureCatalogue to have substitutionGroup="cat:AbstractCT_Catalogue"

**Comment by PeterParslow** [comment]
https://schemas.isotc211.org/19110/fcc/1.0/abstract.xsd contains ref="fcc:Abstract_FeatureCatalogue" (in the declaration of Abstract_FeatureCatalogue_PropertyType).

It includes fcc.xsd

[fcc.xsd](https://schemas.isotc211.org/19110/fcc/1.0/fcc.xsd) includes abstract.xsd & imports https://schemas.isotc211.org/19110/gfc/1.1/gfc.xsd

https://schemas.isotc211.org/19110/gfc/1.1/gfc.xsd includes featureCatalogue.xsd

https://schemas.isotc211.org/19110/gfc/1.1/featureCatalogue.xsd declares element name="FC_FeatureCatalogue" substitutionGroup="fcc:Abstract_FeatureCatalogue"

But I can't see anywhere that fcc:Abstract_FeatureCatalogue is defined; is the "ref=" OK without the target element being defined? Doesn't that make Abstract_FeatureCatalogue_PropertyType unusable? Does that actually no matter i.e. the type is only declared as an artefact of the Schematron processing, and not actually used?

**Comment by ejbleys** [comment]
Abstract_FeatureCatalogue is defined in:
https://schemas.isotc211.org/19110/-/fcc/2.1.0/abstract.xsd
https://schemas.isotc211.org/19110/-/fcc/2.2.0/abstract.xsd
https://schemas.isotc211.org/19110/fcc/1.0/abstract.xsd
