### ISSUE TITLE
Move image term to 19123-1 or 19101-2.

### ISSUE THREAD

**Issue by isotc211** [ISO-TC211/StandardsTracker#348]
<b>Justification:</b> Image term is owned by this standard. However, this standard is not an image standard but acquisition or processing. Image should probably be defined by 19101-2 or 19123-1. 19123-1 intends on handling image CRS or CS.
                                     <b>Proposal:</b> Move image term to 19123-1 or 19101-2.

**Comment by wilkesg** [comment]
During the amendment of 19115-2, this term was not moved. 19123-1 defines image crs, but it is a coverages standard, perhaps image would have a good home with 19101-2.

**Comment by wilkesg** [comment]
At PMGs recommendation we close this issue.
