### ISSUE TITLE
Missing element "describes" from MD_Metadata in metadataBase.xsd

### ISSUE THREAD

**Issue by isotc211** [ISO-TC211/StandardsTracker#354]
<b>Justification:</b> MD_Metadata element name="describes" type="DS_Resource" missing from metadataBase.xsd
The role is expressed in UML as presented in ISO 19115-1:2014 figure 1 (page 6 of edition 1)
                                     <b>Proposal:</b> Add <element maxOccurs="unbounded" minOccurs="1" name="describes" type="mdb:MD_Metadata_PropertyType" id="ISO19115-1.038.x_ISO19115-1.001"/> to metadataBase.xsd after           <element maxOccurs="unbounded" minOccurs="0" name="acquisitionInformation" type="mcc:Abstract_AcquisitionInformation_PropertyType" id="ISO19115-2.031_ISO19115-2.002"/>

**Comment by ejbleys** [comment]
now exists in:
https://schemas.isotc211.org/19115/3/mdb/1.0/metadataBase.xsd
https://schemas.isotc211.org/19115/3/mdb/2.0/metadataBase.xsd
https://schemas.isotc211.org/19115/1/mdb/1.3/metadataBase.xsd
