### ISSUE TITLE
Add parameter (item 120.1) to data dictionary

### ISSUE THREAD

**Issue by isotc211** [ISO-TC211/StandardsTracker#357]
<b>Justification:</b> Element missing from data dictionary. UML class LE_Processing has attribute "parameter; type="LE_ProcessParameter"; [0..*], but it is not in the dataadictionary
                                     <b>Proposal:</b> Add line in data dictionary (potentially 120.1) to reflect the missing attribute from LE_Processing

**Comment by wilkesg** [comment]
Completed as part of Amendment
