### ISSUE TITLE
DS_StereoMate in data dictionary but not in UML

### ISSUE THREAD

**Issue by isotc211** [ISO-TC211/StandardsTracker#362]
<b>Justification:</b> Missing DS_StereoMate Class from UML. OR DS_SterioMate in data dictionary without being in UML
                                     <b>Proposal:</b> Either:
Add to UML
OR
Remove from data dictionary

**Comment by PeterParslow** [comment]
Duplicate of https://github.com/ISO-TC211/StandardsTracker/issues/363
