### ISSUE TITLE
19115-3 Missing XML element from 19115/-3/1.0|2.0/metadataBase.xml 

### ISSUE THREAD

**Issue by ejbleys** [ISO-TC211/StandardsTracker#381]
XML element "describes" [0..*] -> mda:AbstractDS_Resource missing  from both V 1.0 and V 2.0 schemas
Attribute appears in both UML (clause 6.2) and Table B.1.
Issue does not occur in 19115/-1/mdb/1.3/metadataBase.xml

**Comment by PeterParslow** [comment]
I have commented to Evert in response to his email.

**Comment by ejbleys** [comment]
fixed
