### ISSUE TITLE
General concern from AHG06 eGovernment regarding ISO 19101-1 Reference Model

### ISSUE THREAD

**Issue by JanHjelmager** [ISO-TC211/StandardsTracker#439]
Are there more generic reference models to build upon? Old normative references: [18] CSMF – 1998, [3] 2004. [4] 2003, [16] ISO/IEC 2382-1:1993, [2] Level of interoperability-1999, [8] EIF – 2010  (today 2017), [17] RM-ODP 1998

There is a need for strengthen the e-Government part of the reference model and merge part 1 and 2 of the standard into one in order to provide a better coherence.

**Comment by heidivanparys** [comment]
> [18] CSMF – 1998

This one should be removed completely from all ISO/TC 211 standards, see also #432.

**Comment by wilkesg** [comment]
PMG recommends closing this on 17 May 2023.
