### ISSUE TITLE
ISO 19115-1 PT_FreeText: discrepancy between UML and XML?

### ISSUE THREAD

**Issue by heidivanparys** [ISO-TC211/StandardsTracker#468]
Is there a discrepancy between the [UML model for PT_FreeText](http://iso.sparxcloud.com?m=1&o=E41AFE5C-ACD2-4714-9337-6CC826D81C86) and the [XML schema](https://schemas.isotc211.org/19115/-3/lan/1.0/language.xsd)?

![image](https://user-images.githubusercontent.com/11427611/189689565-871699f4-d4c5-4703-8651-7bf01d660d58.png)

```xml
<complexType name="PT_FreeText_PropertyType">
    <complexContent>
      <extension base="gco:CharacterString_PropertyType">
        <sequence minOccurs="0"><!-- minOccurs does not match the multiplicity? -->
          <element ref="lan:PT_FreeText"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
```

Should that multiplicity be 0..* in the UML model, in order to have additional localised strings optional, and to make the XML implementation match? Or am I overlooking something?

I created this issue because of https://github.com/INSPIRE-MIF/application-schemas/issues/69 (note that INSPIRE uses the older schemas from ISO 19139).

**Comment by ejbleys** [comment]
The <sequence minOccurs="0"> in this context allows users to provide a nilReason rather than actual values.
The minOccurs is 1 in the line <element name="PT_FreeText" minOccurs="1" maxOccurs="unbounded"/>

**Comment by ejbleys** [comment]
\<element name="
