### ISSUE TITLE
Missing edition in (presumably) copy-and-paste sentences

### ISSUE THREAD

**Issue by desruisseaux** [ISO-TC211/StandardsTracker#472]
The ISO 19157:2013 specification contains the following minor inconsistencies. Those sentences look like copy-and-paste from a previous definition, where some editions may have been forgotten.

## Table D.15 line 8:
The following text:

> true indicates that an item is _not in conformance_ with its value domain

should be "true indicates that an item _is conforming_ to its value domain".

## Table D.26 line 12:
Identifier "24" duplicates table D.25 line 12. Should be "25".

## Table D.54 and D.55 line 3:
The following text:

> absolute or external accuracy

should be "relative or internal accuracy".

**Comment by PeterParslow** [comment]
ISO 19157:2013 will soon be replaced with ISO 19157-1 (see https://www.iso.org/standard/78900.html). None of these errors occurs in ISO/FDIS 19157-1 which should be available for public review & comment in the next months or so (ISO/DIS 19157-1 was in the ISO enquiry stage Feb - May 2022; some national standards bodies run that publicly).

**Comment by desruisseaux** [comment]
Thanks! I'm closing this issue then.
