### ISSUE TITLE
ISO 19103 should reference ISO 80000-3, Quantities and units -- Part 3: Space and time

### ISSUE THREAD

**Issue by isotc211** [ISO-TC211/StandardsTracker#51]
<b>Justification:</b> GB3 in N3850, Comments received on document N 3806 Recommendations for the specification of cultural and linguistic adaptability (CLA) in ISO/TC 211 standards

2.2.1, Recommendation 25:
ISO 80000 is a good catch: recommend that ISO 19103 be revised to at least reference ISO 80000-3, Quantities and units -- Part 3: Space and time
                                     <b>Proposal:</b> Recommend that ISO 19103 reference ISO 80000-3, Quantities and units -- Part 3: Space and time

**Comment by heidivanparys** [comment]
CD/ISO 19103 mentions ISO 80000-3, this can be closed.
