### ISSUE TITLE
Wrong GML include in ISO 19115-2 XSD

### ISSUE THREAD

**Issue by avillar** [ISO-TC211/StandardsTracker#510]
https://schemas.isotc211.org/19115/-2/gmi/1.0/spatialRepresentationInformation.xsd imports http://www.opengis.net/gml/3.2.1 instead of the canonical URL for the GML XSD which is located at http://schemas.opengis.net/gml/3.2.1/gml.xsd

A redirect has been added by OGC so that http://www.opengis.net/gml/3.2.1 redirects the client to the XSD, but the target document has additional includes that clients resolve again the original URL (pre-redirect), so resolution of those fails.

The ideal solution would be for https://schemas.isotc211.org/19115/-2/gmi/1.0/spatialRepresentationInformation.xsd to import http://schemas.opengis.net/gml/3.2.1/gml.xsd directly instead.

CC @joanma747

**Comment by joanma747** [comment]
Hi,

I detected that, and I believe the fix is that the [https://schemas.isotc211.org/19115/-2/gmi/1.0/](https://schemas.isotc211.org/19115/-2/gmi/1.0/spatialRepresentationInformation.xsd) documents import http://schemas.opengis.net/gml/3.2.1/***.xsd

**Comment by ejbleys** [comment]
Please note https://schemas.isotc211.org/19115/-2/gmi/1.0/spatialRepresentationInformation.xsd is an historic schema having been superseded by:
1st https://schemas.isotc211.org/19115/-3/msr/1.0/spatialRepresentationImagery.xsd
2nd https://schemas.isotc211.org/19115/-3/msr/2.0/spatialRepresentationImagery.xsd
3rd https://schemas.isotc211.org/19115/-2/msr/2.2.0/spatialRepresentationImagery.xsd
     a https://schemas.isotc211.org/19115/-2/msr/2.2.1/spatialRepresentationImagery.xsd is being developed to take advantage of ISO 19157-1:2023, but it has to be tested before it can proceed to publication.
For those who are unable to migrate their systems to more current versions I will version the .../gmi/1.0/... to .../gmi/1.1/... picking up the updated GML 3.2.1, but be aware you will need to update your system to take advantage  of the updates.
